# Configuration for Dependabot version updates
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      actions:
        patterns: ["*"]
    labels:
      - "dependencies"
    commit-message:
      prefix: "Actions"
      include: "scope"
    open-pull-requests-limit: 5

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      dev-dependencies:
        patterns:
          - "automattic/*"
          - "dealerdirect/*"
          - "php-parallel-lint/*"
          - "phpcompatibility/*"
          - "phpunit/*"
          - "squizlabs/*"
          - "yoast/*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "Composer"
      include: "scope"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
